### ISSUE TITLE
Getting error, unable to aquire token

### ISSUE THREAD

**Issue by spuder** [pendrica/azure-credentials#1]
This gem looks fantastic. I can't wait to use it.  I'm getting this error when trying to use the gem. I'm able to login to azure via the browser using the same credentials. Any assistance would be appreciated. 

```bash
 azure-credentials -v --log_level debug
DEBUG [2016-04-25 11:10:27] Command line options: {:subscription_id=>nil, :role=>"Contributor", :type=>"chef", :log_level=>:debug, :output_file=>"./credentials", :out_to_screen=>true}
Enter your Azure AD username (user@domain.com): bob@example.com
Enter your password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
INFO [2016-04-25 11:10:37] Authenticating to Azure Active Directory
DEBUG [2016-04-25 11:10:38] Request: https://login.windows.net/Common/oauth2/token (POST) resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id=xxxxxxxxxxxxxx&grant_type=password&username=bob@example.com&scope=openid&password=xxxxxxxxxxxxx
DEBUG [2016-04-25 11:10:38] Response: {"error":"invalid_grant","error_description":"AADSTS50034: To sign into this application the account must be added to the example.com directory.\r\nTrace ID: xxxxxxxxx\r\nCorrelation ID: xxxxxxxx\r\nTimestamp: 2016-04-25 17:10:30Z","error_codes":[50034],"timestamp":"2016-04-25 17:10:30Z","trace_id":"xxxxxxxx","correlation_id":"xxxxxxxxxx"}
ERROR [2016-04-25 11:10:38] Unable to acquire token from Azure AD provider.
/Users/sowen/.rvm/gems/ruby-2.2.0/gems/azure-credentials-0.1.1/lib/azure/utility/credentials.rb:138:in `initialize': Unable to acquire token from Azure AD provider. (RuntimeError)
	from /Users/sowen/.rvm/gems/ruby-2.2.0/gems/azure-credentials-0.1.1/bin/azure-credentials:4:in `new'
	from /Users/sowen/.rvm/gems/ruby-2.2.0/gems/azure-credentials-0.1.1/bin/azure-credentials:4:in `<top (required)>'
	from /Users/sowen/.rvm/gems/ruby-2.2.0/bin/azure-credentials:23:in `load'
	from /Users/sowen/.rvm/gems/ruby-2.2.0/bin/azure-credentials:23:in `<main>'
	from /Users/sowen/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sowen/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by andrewelizondo** [comment]
+1 I'm hitting the exact same error message when using a basic Microsoft account.

**Comment by stuartpreston** [comment]
Yep only accounts that originate in Azure AD are currently supported. I assume the account in question in a Microsoft account?

**Comment by vzabauski** [comment]
I'm getting the following error when I'm using Azure AD account. Same thing appears when I'm using MS account.

```
[vagrant@puppet ~]$ azure-credentials -u ##########@#######.onmicrosoft.com -p "#######" -o ~/azure.conf -t puppet -v
INFO [2016-07-22 09:59:05] Authenticating to Azure Active Directory
ERROR [2016-07-22 09:59:08] Unable to acquire token from Azure AD provider.
/home/vagrant/.gem/ruby/gems/azure-credentials-0.1.1/lib/azure/utility/credentials.rb:138:in `initialize': Unable to acquire token from Azure AD provider. (RuntimeError)
        from /home/vagrant/.gem/ruby/gems/azure-credentials-0.1.1/bin/azure-credentials:4:in `new'
        from /home/vagrant/.gem/ruby/gems/azure-credentials-0.1.1/bin/azure-credentials:4:in `<top (required)>'
        from /home/vagrant/bin/azure-credentials:23:in `load'
        from /home/vagrant/bin/azure-credentials:23:in `<main>'
```

**Comment by stuartpreston** [comment]
Hey

I just tested using an account that was setup with a Microsoft Account as the Global Administrator, and added a new AAD account as a co-administrator:

![image](https://cloud.githubusercontent.com/assets/6384654/17186339/b3d2283e-542c-11e6-8484-4126d5358c3f.png)

![image](https://cloud.githubusercontent.com/assets/6384654/17186381/e4fb4daa-542c-11e6-8fd9-3c60ea905c3b.png)

I was then able to use the tool successfully to create the service principal though.  Please could you re-check given the above info.

You can get lots of debug by adding ```-l debug``` to the command, feel free to send this to me at the address on my profile if you want me to take a look through.

**Comment by vzabauski** [comment]
Yeah, it's fine. I forgot to update the password in AD account.
